# Generated by Django 4.1.1 on 2023-08-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentryIssue",
            fields=[
                (
                    "hash",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("title", models.TextField()),
                ("where", models.TextField()),
                ("exception_value", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SentryEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="example: 7bfcbdef7a754da985f8e69d64d1299c",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("json", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="minisentry.sentryissue",
                    ),
                ),
            ],
        ),
    ]
